### ISSUE TITLE
Write software engineering processes document

### ISSUE THREAD

**Issue by eric5rivera** [braille-book/calendar-assignment#3]
Generated a one or two page document describing the software engineering processes your team adopts. I suggest continuing with the ICS 314 approach.

**Comment by eric5rivera** [comment]
we will follow Issue Driven Project Management very similar to guidelines [here](http://courses.ics.hawaii.edu/ics314f19/morea/project-management/reading-guidelines-idpm.html)

**Comment by michaeljohnson127** [comment]
Good old 314 format
